// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN7rxl7h0mXfxj0Op-g-qZ13r7KZW827A',
    appId: '1:945386292959:web:af5f69574f84ddf7718b6a',
    messagingSenderId: '945386292959',
    projectId: 'venus-assistant-app',
    authDomain: 'venus-assistant-app.firebaseapp.com',
    storageBucket: 'venus-assistant-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuGAzDDi4VGsl4IA2FM2N_A4e1SOVA0Tg',
    appId: '1:945386292959:android:298274f1a470f6b0718b6a',
    messagingSenderId: '945386292959',
    projectId: 'venus-assistant-app',
    storageBucket: 'venus-assistant-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArXKvn3as_Xt0yApjmtFrje8Ha5Wrk4VA',
    appId: '1:945386292959:ios:3cec65a2769f98d9718b6a',
    messagingSenderId: '945386292959',
    projectId: 'venus-assistant-app',
    storageBucket: 'venus-assistant-app.firebasestorage.app',
    iosBundleId: 'com.example.venusAssistantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArXKvn3as_Xt0yApjmtFrje8Ha5Wrk4VA',
    appId: '1:945386292959:ios:3cec65a2769f98d9718b6a',
    messagingSenderId: '945386292959',
    projectId: 'venus-assistant-app',
    storageBucket: 'venus-assistant-app.firebasestorage.app',
    iosBundleId: 'com.example.venusAssistantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN7rxl7h0mXfxj0Op-g-qZ13r7KZW827A',
    appId: '1:945386292959:web:6aa145f7b8b12cdc718b6a',
    messagingSenderId: '945386292959',
    projectId: 'venus-assistant-app',
    authDomain: 'venus-assistant-app.firebaseapp.com',
    storageBucket: 'venus-assistant-app.firebasestorage.app',
  );
}
